### ISSUE TITLE
Error - {"code": 40101, "message": "Missing request credentials", "stat": "FAIL"} How to resolve it? 

### ISSUE THREAD

**Issue by RobinMalhotraa** [duosecurity/duo_client_python#148]
```
import java.io.*;
import java.net.URL;
import java.net.HttpURLConnection;

public class duo {
    
    public static void main(String[] args) throws IOException, InterruptedException {
// Create a neat value object to hold the URL

  URL url;
      url = new URL("https://api-e9770554.duosecurity.com/admin/v1/users?username=#get_user.userid#");



// Open a connection(?) on the URL(??) and cast the response(???)
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

// Now it's "open", we can set the request method, headers etc.
        connection.setRequestProperty("accept", "application/json");

// This line makes the request
        InputStream responseStream = connection.getInputStream();

 }

}

```

**Comment by AaronAtDuo** [comment]
@RobinMalhotraa Perhaps you did not include it here, but I don't see any code that handles the signing of the request, which is required by the Admin API: https://duo.com/docs/adminapi#authentication

I would recommend that you use our Java client library, also available on Github, because it can handle the signing of the request for you.  You can see some examples of how to use it at https://github.com/duosecurity/duo_client_java/blob/master/duo-example-admin/src/main/java/com/duosecurity/example/DuoAdmin.java

**Comment by RobinMalhotraa** [comment]
I am new to this. I don't know where to implement it. Can you add it to the above code?

**Comment by AaronAtDuo** [comment]
The example at https://github.com/duosecurity/duo_client_java/blob/master/duo-example-admin/src/main/java/com/duosecurity/example/DuoAdmin.java#L120 shows how to fetch multiple users, it should be very similar to what you need.  That's probably the best example to follow.

**Comment by RobinMalhotraa** [comment]
Thanks for this but the problem is Java is really new for me.

**Comment by AaronAtDuo** [comment]
I understand how it is when you're trying to pick up a new language, hope it goes well for you.  Trying to use our Java API to learn on is probably a more difficult early step than you want though, it's a little tricky to use.

I might suggest a 'live' API explorer like Google's (https://developers.google.com/explorer-help/guides/code_samples) that might be more suitable for getting familiar with API clients.
